export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USRE_COMMIT = 'LOGIN_USRE_COMMIT';
export const LOGIN_USER_ROLLBACK = 'LOGIN_USER_ROLLBACK';
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH';

export const SYSTEM_LIST = 'SYSTEMS';
export const SYSTEMS_COMMIT = 'SYSTEMS_COMMIT';
export const SYSTEMS_ROLLBACK = 'SYSTEMS_ROLLBACK';



export const API_LOADING = 'API_LOADING';
export const OPERATION_FAILED = 'OPERATION_FAILED';

export const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';

// Authentication
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SET_SCOPE_SUCCESS = 'SET_SCOPE_SUCCESS';
export const FORGOT_SUCCESS = 'FORGOT_SUCCESS';

// User
export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

// Wardrobe
export const GET_WARDROBE_USER_LIST_SUCCESS = 'GET_WARDROBE_USER_LIST_SUCCESS';
export const GET_WARDROBE_POST_LIST_SUCCESS = 'GET_WARDROBE_POST_LIST_SUCCESS';
export const ADD_WARDROBE_POST_ITEM_SUCCESS = 'ADD_WARDROBE_POST_ITEM_SUCCESS';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const SEND_LIKE_NOTIFICATION_SUCCESS = 'SEND_LIKE_NOTIFICATION_SUCCESS';
export const SEND_COMMENT_NOTIFICATION_SUCCESS = 'SEND_COMMENT_NOTIFICATION_SUCCESS';
export const SEND_FOLLOW_INVITATION_SUCCESS = 'SEND_FOLLOW_INVITATION_SUCCESS';

// World
export const GET_WORLD_LIST_SUCCESS = 'GET_WORLD_LIST_SUCCESS';
export const GET_WORLD_DETAIL_SUCCESS = 'GET_WORLD_DETAIL_SUCCESS';
export const ADD_WORLD_INFO_SUCCESS = 'ADD_WORLD_INFO_SUCCESS';

// Faslance
export const GET_FASLANCE_LIST_SUCCESS = 'GET_FASLANCE_LIST_SUCCESS';
export const GET_FASLANCE_TIPS_LIST_SUCCESS = 'GET_FASLANCE_TIPS_LIST_SUCCESS';
export const ADD_FASLANCE_TIP_SUCCESS = 'ADD_FASLANCE_TIP_SUCCESS';
export const ADD_FASLANCE_ACCOUNT_SUCCESS = 'ADD_FASLANCE_ACCOUNT_SUCCESS';

// Notification
export const GET_NOTIFICATION_LIKE_LIST_SUCCESS = 'GET_NOTIFICATION_LIKE_LIST_SUCCESS';
export const GET_NOTIFICATION_COMMENT_LIST_SUCCESS = 'GET_NOTIFICATION_COMMENT_LIST_SUCCESS';

// Profile
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';


// FolderPost
export const GET_FOLDERPOST_LIST_SUCCESS = 'GET_FOLDERPOST_LIST_SUCCESS';
export const EDIT_FOLDERPOST_SUCCESS = 'EDIT_FOLDERPOST_SUCCESS';
export const ADD_FOLDERPOST_SUCCESS = 'ADD_FOLDERPOST_SUCCESS';
